// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbitI7XK7KOYuMnJ3WcwASHJ19rOhbaAU',
    appId: '1:207339661289:web:e71159c97f0e8b1d648d78',
    messagingSenderId: '207339661289',
    projectId: 'microsleep-2b9d9',
    authDomain: 'microsleep-2b9d9.firebaseapp.com',
    databaseURL: 'https://microsleep-2b9d9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'microsleep-2b9d9.firebasestorage.app',
    measurementId: 'G-B82WRG7QS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD56eOM7_gqyMO3edtgNuybdUlgyNwO5NY',
    appId: '1:207339661289:android:30abf24ea04da774648d78',
    messagingSenderId: '207339661289',
    projectId: 'microsleep-2b9d9',
    databaseURL: 'https://microsleep-2b9d9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'microsleep-2b9d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC2O86O1a2G-cZBTuPRQM8FX7DMpgfTV0',
    appId: '1:207339661289:ios:13472a026a9f899e648d78',
    messagingSenderId: '207339661289',
    projectId: 'microsleep-2b9d9',
    databaseURL: 'https://microsleep-2b9d9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'microsleep-2b9d9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC2O86O1a2G-cZBTuPRQM8FX7DMpgfTV0',
    appId: '1:207339661289:ios:13472a026a9f899e648d78',
    messagingSenderId: '207339661289',
    projectId: 'microsleep-2b9d9',
    databaseURL: 'https://microsleep-2b9d9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'microsleep-2b9d9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbitI7XK7KOYuMnJ3WcwASHJ19rOhbaAU',
    appId: '1:207339661289:web:d23e6c428178d30e648d78',
    messagingSenderId: '207339661289',
    projectId: 'microsleep-2b9d9',
    authDomain: 'microsleep-2b9d9.firebaseapp.com',
    databaseURL: 'https://microsleep-2b9d9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'microsleep-2b9d9.firebasestorage.app',
    measurementId: 'G-JTT4M4RC3J',
  );
}
